[build]
target = "riscv32imac-unknown-none-elf"

[target."riscv32imac-unknown-none-elf"]
rustflags = [
#  "-C", "link-arg=-Tlink.x",
]
# runner = "riscv64-unknown-elf-gdb -q -x openocd.gdb"
# runner = "riscv-none-embed-gdb -q -x openocd.gdb"
# runner = "gdb -q -x openocd.gdb"
# runner = "wlink -v flash"

runner = "wlink -v flash --enable-sdi-print --watch-serial"
# runner = "wlink -v flash"
